export const fishList = [
    {
        jpName: "maguro",
        enName: "tuna",
        color: "red",
        texture: "soft",
        notes: "the leanest tuna cut",
        cooked: false,
    },
    {
        jpName: "saumon",
        enName: "salmon",
        color: "orange",
        texture: "soft",
        notes: "delicious",
        cooked: false,
    },
    {
        jpName: "uni",
        enName: "sea urchin",
        color: "yellow",
        texture: "soft",
        notes: "smooth like butter",
        cooked: false,
    },
    {
        jpName: "unagi",
        enName: "freshwater eel",
        color: "brown",
        texture: "soft",
        notes: "typically Anguilla japonica",
        cooked: true,
        family: "Anguillidae",
        genus: "Anguilla",
    },
    {
        jpName: "tamago",
        enName: "egg",
        color: "yellow",
        texture: "firm",
        notes: "Often mixed with sake, mirin, sugar, and/or soy sauce",
        cooked: true,
    },
    {
        jpName: "ika",
        enName: "squid",
        color: "white",
        texture: "chewy",
        notes: "specific, squid mantle, which is the head part",
        cooked: false,
    },
    {
        jpName: "anago",
        enName: "saltwater eel",
        color: "brown",
        texture: "soft",
        notes: "commonly from the genus Conger",
        cooked: true,
        family: "Congridae",
        genus: "Conger"
    },
    {
        jpName: "hotate",
        enName: "scallop",
        color: "white",
        texture: "soft",
        notes: "wide range of species eaten",
        cooked: false,
        family: "Pectinidae"
    },
    {
        jpName: "aji",
        enName: "horse mackerel",
        color: "red",
        texture: "soft",
        notes: "often cured with vinegar/ Best Season: Summer",
        cooked: false,
        family: "Carangidae"
    },
    {
        jpName: "sanma",
        enName: "mackerel pike",
        color: "brown, pink",
        texture: "soft",
        notes: "also known as Pacific Saury. Best Season: Fall",
        cooked: false,
        family: "Scomberesocidae"
    },
    {
        jpName: "saba",
        enName: "mackerel",
        color: "red",
        texture: "soft",
        notes: "usually cured with vinegar, also known as the chub, or Pacific Chub Mackerel. Best Season: Fall",
        cooked: true,
    },
]